POST http://localhost:3000/api/patients
content-type: application/json

{
    "name": "Tuomas Testaaja",
    "dateOfBirth": "2000-01-01",
    "ssn": "123456-12A",
    "gender": "male",
    "occupation": "Tester"
}
